# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mapyrus-jar
          path: target/mapyrus-*.jar

      - name: Build with Maven (war)
        run: mvn -B compile war:war --file pom.xml
      - name: Archive production artifacts (war)
        uses: actions/upload-artifact@v2
        with:
          name: mapyrus-war
          path: target/mapyrus-*.war
